### ISSUE TITLE
Issue on Raspberry Pi OS Buster, Pi Zero W, Python 3.7

### ISSUE THREAD

**Issue by grainsoflight** [cdgriffith/darkroom#2] opened 2020-09-20 02:15 UTC
Hi! Im getting the following error on OS Buster, pi Zero W, Python 3.7:

> Traceback (most recent call last):
>   File "darkroom/main.py", line 6, in <module>
>     from pynput import keyboard
>   File "/home/pi/.local/lib/python3.7/site-packages/pynput/__init__.py", line 40, in <module>
>     from . import keyboard
>   File "/home/pi/.local/lib/python3.7/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
>     backend = backend(__name__)
>   File "/home/pi/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 82, in backend
>     if resolutions else '')
> ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))
> 
> Try one of the following resolutions:
> 
>  * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
> 

I have the Dot Matrix up and running and all the dependencies installed. The one thing I noticed that was different from your build is that I am running python3, whereas your build appears to be on python2.7. I dont have the option to run 2.7 as luma.led_matrix is no longer supports it. Any help would be greatly appreciated!

**Comment by cdgriffith** [comment] 2020-10-09 14:52
duplicate of https://github.com/cdgriffith/darkroom/issues/3#issuecomment-705291756

**Closed as completed by cdgriffith** 2020-10-09 14:52 UTC
